version: '3'

services:

  web:
    build: ./web
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - USER_URL=http://192.168.99.100:3000/user
      - BOOK_URL=http://192.168.99.100:3000/book
    command: ["npm", "run", "dev"]

  gateway:
    build: ./gateway
    volumes:
      - ./gateway:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - USER_ENDPOINT=http://user:3001
      - BOOK_ENDPOINT=http://book:3002
    command: ["npm", "run", "dev"]


  user:
    build: ./user
    volumes:
      - ./user/:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment: 
      - NODE_ENV=development
      - DB_CONNECT_STRING=${USER_DB_CONNECT_STRING}
    command: ["npm", "run", "dev"]

  book:
    build: ./book
    volumes:
      - ./book/:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    environment: 
      - NODE_ENV=development
      - DB_CONNECT_STRING=${BOOK_DB_CONNECT_STRING}
    command: ["npm", "run", "dev"]

  # mongo:
  #   image: mongo
  #   volumes:
  #     - mongo:/var/lib/mongodb
  #   ports:
  #     - "27017:27017"
    # networks:
    #  - micro-network
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./web/public:/srv/www/static
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - web
  #     - book
  #     - user
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root
